FROM node:16-alpine AS builder
ENV NODE_ENV development

# Add a work directory
WORKDIR /app

# Cache and Install dependencies
COPY package.json .
COPY yarn.lock .
# RUN is for a single-use command in the build process of the container
RUN yarn install

# Copy app files
COPY . .

# Start the app; think in the context of container lifecycle (starting container)
CMD [ "yarn", "start" ]