flowchart TB
    subgraph App
        subgraph NavBar
        end
        subgraph Window List
            subgraph GraphComponent
                subgraph LineChart
                end
            end
        end
        subgraph Window 
            subgraph RidesMeasurementComponent
                subgraph ListItemButton Ride
                end
                subgraph ListItemButton Measurement
                end
            end
        end
        subgraph MapComponent
            subgraph Map
            end
            subgraph Zoom/Layer controls
            end
            subgraph PolyLine List
            end
        end
    end