flowchart BT
    subgraph NavBar
        handleClose([handleClose])
        handleClick([handleClick])
        anchorEl{{anchorEl}}
        subgraph List
            subgraph ListItemButton
            end
        end
    end