flowchart BT
    subgraph App
        subgraph NavBar
        end
        subgraph WindowRides
            subgraph RidesMeasurementsComponent
            end
        end
        subgraph WindowGraph
            subgraph GraphComponent
            end
        end
        subgraph Map
        end

        addGraphComponent([addGraphComponent]) <--> RidesMeasurementsComponent
        addGraphComponent -- UniqueID --> graphComponentsList{{graphComponentsList}}
        addGraphComponent -- Add lat lon data as PolyLine --> polyLinePoints{{polyLinePoints}}
        
        polyLinePoints -- Show list of PolyLines --> Map

        removeGraphComponent([removeGraphComponent]) -- Remove GraphComponent --> graphComponentsList
        removeGraphComponent -- Remove PolyLine --> polyLinePoints

        graphComponentsList -- Add GraphComponent --> WindowGraph

        NavBar --> setRidesIsRendered{{setRidesIsRendered}}

        setRidesIsRendered <-- True / False --> WindowRides

        WindowGraph --> removeGraphComponent
        
    end

    API -- /trips AND /measurement/types --> RidesMeasurementsComponent
    API -- /trips/acceleration/tripID --> GraphComponent
    API -- /trips/segments/tripID --> addGraphComponent
    