flowchart BT
    handleRideItemClick -- tripID --> addGraphComponent([addGraphComponent])

    API <-- /trips --> fetchRides
    API <-- /measurement/types --> fetchMeasurements

    subgraph WindowRides
        subgraph RidesMeasurementsComponent
            
            fetchRides([fetchRides]) -- setRidesInfo --> rideInfos{{rideInfos}}

            fetchMeasurements([fetchMeasurements]) -- setMeasurementsInfo --> measurementInfos{{measurementInfos}}
            
            ListItemRide -- tripID --> handleRideItemClick([handleRideItemClick])
            
            ListItemMeasurement --> handleMeasurementItemClick([handleMeasurementItemClick])

            rideInfos{{rideInfos}} -- Show Rides --> ListRides

            measurementInfos{{measurementInfos}} -- Show Measurements --> ListMeasurements
            
            handleMeasurementItemClick -- setSelectedMeasurements --> selectedMeasurements{{selectedMeasurements}}

            handleRideItemClick -- setSelectedRides --> selectedRides{{selectedRides}}
            subgraph ListRides
                ListItemRide
            end
            subgraph ListMeasurements
                ListItemMeasurement
            end
        end
    end