flowchart LR
    API --> polyLinePoints
    API --> RidesMeasurementComponent
    API --> RidesMeasurementComponent
    API --> graphContent
    
    subgraph API
    end
    subgraph App
        graphComponentList([graphComponentList])
        polyLinePoints([polyLinePoints])
        rideIsRendered([rideIsRendered])
        uniqueID([uniqueID])
        uniqueZ([uniqueZ])

        uniqueZ --> RidesMeasurementComponent
        uniqueZ --> GraphComponent
        
        rideIsRendered<--->ListItemButton
        rideIsRendered --> RidesMeasurementComponent
        
        uniqueID --> GraphComponent
        graphComponentList--> GraphComponent

        polyLinePoints  --> newPolyLineList([newPolyLineList])
        newPolyLineList --> PolyLineList

        ListItemButtonRide --> GraphComponent
        ListItemButtonMeasurement --> RidesMeasurementComponent

        subgraph NavBar
            ListItemButton
        end
        subgraph WindowList
            subgraph GraphComponent
                graphContent([graphContent]) --> LineChart
                subgraph LineChart
                end
            end
        end
        subgraph Window
            subgraph RidesMeasurementComponent
                subgraph ListItemButtonRide
                end
                subgraph ListItemButtonMeasurement
                end
            end
        end
        subgraph MapContainer
            subgraph Zoom/LayerControls
            end
            subgraph PolyLineList
            end
        end
    end